### ISSUE TITLE
Contextual wells (or similar container)

### ISSUE THREAD

**Issue by stuartgiles** [holidayextras/brands#9]
@stuartgiles, @nassimdonald and @jodiedoubleday have discussed this but not yet reached a conclusion.

We need a parent element class which we can use to segment our page content. This could be with a background colour.

In the past @stuartgiles has use 'wells' in Essential Travel and HX.

e.g.

- well-default
- well-primary
- well-info
- well-warning
- well-danger

We could chose a different name (as 'wells' have bootstrap connotations which are being removed).

This is a perfect opportunity for a Global element which can be re-used by all brands.

**Comment by nassimdonald** [comment]
I have been working on this in the footer branch (uxui-172) and basically ended up with a `.well-variant` mixin. It works for the basic cases (styling text, links, hr etc.) but will not effectively style other components like navs and buttons etc. One quick solution I can think of is creating a 'light' and 'dark' version (or 'normal' and 'inverse') of all components that may get lost in either a dark or light background, and target them within the well-variant mixin. This would result in a lot of extra compiled CSS but can't imagine any solution that wouldn't.

**Comment by nassimdonald** [comment]
This has been resolved with the new *background-variant* and *blocks* work in *globals* brand.
